// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/sayze/friendly-api/internal/friend/domain"
	"io"
	"sync"
)

// Ensure, that ServiceMock does implement Service.
// If this is not the case, regenerate this file with moq.
var _ Service = &ServiceMock{}

// ServiceMock is a mock implementation of Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked Service
//		mockedService := &ServiceMock{
//			CreateFunc: func(ctx context.Context, name string, image io.Reader, filename string) (*domain.Friend, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*domain.Friend, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, search string) ([]*domain.Friend, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, name string, image io.Reader, filename string) (*domain.Friend, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedService in code that requires Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, name string, image io.Reader, filename string) (*domain.Friend, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*domain.Friend, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, search string) ([]*domain.Friend, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, name string, image io.Reader, filename string) (*domain.Friend, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Image is the image argument value.
			Image io.Reader
			// Filename is the filename argument value.
			Filename string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Search is the search argument value.
			Search string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Name is the name argument value.
			Name string
			// Image is the image argument value.
			Image io.Reader
			// Filename is the filename argument value.
			Filename string
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ServiceMock) Create(ctx context.Context, name string, image io.Reader, filename string) (*domain.Friend, error) {
	if mock.CreateFunc == nil {
		panic("ServiceMock.CreateFunc: method is nil but Service.Create was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Name     string
		Image    io.Reader
		Filename string
	}{
		Ctx:      ctx,
		Name:     name,
		Image:    image,
		Filename: filename,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, name, image, filename)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedService.CreateCalls())
func (mock *ServiceMock) CreateCalls() []struct {
	Ctx      context.Context
	Name     string
	Image    io.Reader
	Filename string
} {
	var calls []struct {
		Ctx      context.Context
		Name     string
		Image    io.Reader
		Filename string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ServiceMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("ServiceMock.DeleteFunc: method is nil but Service.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedService.DeleteCalls())
func (mock *ServiceMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ServiceMock) Get(ctx context.Context, id int64) (*domain.Friend, error) {
	if mock.GetFunc == nil {
		panic("ServiceMock.GetFunc: method is nil but Service.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedService.GetCalls())
func (mock *ServiceMock) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *ServiceMock) List(ctx context.Context, search string) ([]*domain.Friend, error) {
	if mock.ListFunc == nil {
		panic("ServiceMock.ListFunc: method is nil but Service.List was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Search string
	}{
		Ctx:    ctx,
		Search: search,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, search)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedService.ListCalls())
func (mock *ServiceMock) ListCalls() []struct {
	Ctx    context.Context
	Search string
} {
	var calls []struct {
		Ctx    context.Context
		Search string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ServiceMock) Update(ctx context.Context, id int64, name string, image io.Reader, filename string) (*domain.Friend, error) {
	if mock.UpdateFunc == nil {
		panic("ServiceMock.UpdateFunc: method is nil but Service.Update was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       int64
		Name     string
		Image    io.Reader
		Filename string
	}{
		Ctx:      ctx,
		ID:       id,
		Name:     name,
		Image:    image,
		Filename: filename,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, name, image, filename)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedService.UpdateCalls())
func (mock *ServiceMock) UpdateCalls() []struct {
	Ctx      context.Context
	ID       int64
	Name     string
	Image    io.Reader
	Filename string
} {
	var calls []struct {
		Ctx      context.Context
		ID       int64
		Name     string
		Image    io.Reader
		Filename string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
