// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"context"
	"io"
	"sync"
)

// Ensure, that FriendRepositoryMock does implement FriendRepository.
// If this is not the case, regenerate this file with moq.
var _ FriendRepository = &FriendRepositoryMock{}

// FriendRepositoryMock is a mock implementation of FriendRepository.
//
//	func TestSomethingThatUsesFriendRepository(t *testing.T) {
//
//		// make and configure a mocked FriendRepository
//		mockedFriendRepository := &FriendRepositoryMock{
//			AllFunc: func(ctx context.Context, search string) ([]*Friend, error) {
//				panic("mock out the All method")
//			},
//			CountFunc: func(ctx context.Context) (int, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, name string, image string) (*Friend, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*Friend, error) {
//				panic("mock out the Get method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, name string, image string) (*Friend, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedFriendRepository in code that requires FriendRepository
//		// and then make assertions.
//
//	}
type FriendRepositoryMock struct {
	// AllFunc mocks the All method.
	AllFunc func(ctx context.Context, search string) ([]*Friend, error)

	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context) (int, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, name string, image string) (*Friend, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*Friend, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, name string, image string) (*Friend, error)

	// calls tracks calls to the methods.
	calls struct {
		// All holds details about calls to the All method.
		All []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Search is the search argument value.
			Search string
		}
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Image is the image argument value.
			Image string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Name is the name argument value.
			Name string
			// Image is the image argument value.
			Image string
		}
	}
	lockAll    sync.RWMutex
	lockCount  sync.RWMutex
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// All calls AllFunc.
func (mock *FriendRepositoryMock) All(ctx context.Context, search string) ([]*Friend, error) {
	if mock.AllFunc == nil {
		panic("FriendRepositoryMock.AllFunc: method is nil but FriendRepository.All was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Search string
	}{
		Ctx:    ctx,
		Search: search,
	}
	mock.lockAll.Lock()
	mock.calls.All = append(mock.calls.All, callInfo)
	mock.lockAll.Unlock()
	return mock.AllFunc(ctx, search)
}

// AllCalls gets all the calls that were made to All.
// Check the length with:
//
//	len(mockedFriendRepository.AllCalls())
func (mock *FriendRepositoryMock) AllCalls() []struct {
	Ctx    context.Context
	Search string
} {
	var calls []struct {
		Ctx    context.Context
		Search string
	}
	mock.lockAll.RLock()
	calls = mock.calls.All
	mock.lockAll.RUnlock()
	return calls
}

// Count calls CountFunc.
func (mock *FriendRepositoryMock) Count(ctx context.Context) (int, error) {
	if mock.CountFunc == nil {
		panic("FriendRepositoryMock.CountFunc: method is nil but FriendRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedFriendRepository.CountCalls())
func (mock *FriendRepositoryMock) CountCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *FriendRepositoryMock) Create(ctx context.Context, name string, image string) (*Friend, error) {
	if mock.CreateFunc == nil {
		panic("FriendRepositoryMock.CreateFunc: method is nil but FriendRepository.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Image string
	}{
		Ctx:   ctx,
		Name:  name,
		Image: image,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, name, image)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedFriendRepository.CreateCalls())
func (mock *FriendRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Name  string
	Image string
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Image string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *FriendRepositoryMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("FriendRepositoryMock.DeleteFunc: method is nil but FriendRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedFriendRepository.DeleteCalls())
func (mock *FriendRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *FriendRepositoryMock) Get(ctx context.Context, id int64) (*Friend, error) {
	if mock.GetFunc == nil {
		panic("FriendRepositoryMock.GetFunc: method is nil but FriendRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedFriendRepository.GetCalls())
func (mock *FriendRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *FriendRepositoryMock) Update(ctx context.Context, id int64, name string, image string) (*Friend, error) {
	if mock.UpdateFunc == nil {
		panic("FriendRepositoryMock.UpdateFunc: method is nil but FriendRepository.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		Name  string
		Image string
	}{
		Ctx:   ctx,
		ID:    id,
		Name:  name,
		Image: image,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, name, image)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedFriendRepository.UpdateCalls())
func (mock *FriendRepositoryMock) UpdateCalls() []struct {
	Ctx   context.Context
	ID    int64
	Name  string
	Image string
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		Name  string
		Image string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// Ensure, that ImageStoreMock does implement ImageStore.
// If this is not the case, regenerate this file with moq.
var _ ImageStore = &ImageStoreMock{}

// ImageStoreMock is a mock implementation of ImageStore.
//
//	func TestSomethingThatUsesImageStore(t *testing.T) {
//
//		// make and configure a mocked ImageStore
//		mockedImageStore := &ImageStoreMock{
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			UploadFunc: func(ctx context.Context, img io.Reader, filename string, id string) (string, error) {
//				panic("mock out the Upload method")
//			},
//		}
//
//		// use mockedImageStore in code that requires ImageStore
//		// and then make assertions.
//
//	}
type ImageStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// UploadFunc mocks the Upload method.
	UploadFunc func(ctx context.Context, img io.Reader, filename string, id string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Upload holds details about calls to the Upload method.
		Upload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Img is the img argument value.
			Img io.Reader
			// Filename is the filename argument value.
			Filename string
			// ID is the id argument value.
			ID string
		}
	}
	lockDelete sync.RWMutex
	lockUpload sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *ImageStoreMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("ImageStoreMock.DeleteFunc: method is nil but ImageStore.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedImageStore.DeleteCalls())
func (mock *ImageStoreMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Upload calls UploadFunc.
func (mock *ImageStoreMock) Upload(ctx context.Context, img io.Reader, filename string, id string) (string, error) {
	if mock.UploadFunc == nil {
		panic("ImageStoreMock.UploadFunc: method is nil but ImageStore.Upload was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Img      io.Reader
		Filename string
		ID       string
	}{
		Ctx:      ctx,
		Img:      img,
		Filename: filename,
		ID:       id,
	}
	mock.lockUpload.Lock()
	mock.calls.Upload = append(mock.calls.Upload, callInfo)
	mock.lockUpload.Unlock()
	return mock.UploadFunc(ctx, img, filename, id)
}

// UploadCalls gets all the calls that were made to Upload.
// Check the length with:
//
//	len(mockedImageStore.UploadCalls())
func (mock *ImageStoreMock) UploadCalls() []struct {
	Ctx      context.Context
	Img      io.Reader
	Filename string
	ID       string
} {
	var calls []struct {
		Ctx      context.Context
		Img      io.Reader
		Filename string
		ID       string
	}
	mock.lockUpload.RLock()
	calls = mock.calls.Upload
	mock.lockUpload.RUnlock()
	return calls
}
